filebeat.inputs:

- type: filestream
  id: mftcontainer-admin-server
  include_lines: ['^####']
  exclude_lines: ['<Info>']
  tags: ["mftcontainer-admin-server-log"]
  paths:
  - /usr/share/logs/MFTVolume/MFTDomain/servers/AdminServer/logs/AdminServer.log
  enabled: true

- type: filestream
  id: mftcontainer-mftserver1-logs
  include_lines: ['^####']
  exclude_lines: ['<Info>']
  tags: ["mftcontainer-mftserver1-logs"]
  paths:
  - /usr/share/logs/MFTVolume/MFTDomain/servers/mft_server1/logs/mft_server1.log
  enabled: true

- type: filestream
  id: mftcontainer-mftserver1-access-logs
  include_lines: ['^[0-9]{4}\-[0-9]{2}\-[0-9]{2}']
  exclude_lines: ['isSoaServerReady']
  tags: ["mftcontainer-mftserver1-access-logs"]
  paths:
  - /usr/share/logs/MFTVolume/MFTDomain/servers/mft_server1/logs/access.log
  enabled: true


- type: filestream
  id: mftcontainer-mftserver1-diagnostic-logs
  include_lines: ['^\[[0-9]{4}\-[0-9]{2}\-[0-9]{2}']
  exclude_lines: ['\[NOTIFICATION\]']
  tags: ["mftcontainer-mftserver1-diagnostic-logs"]
  paths:
  - /usr/share/logs/MFTVolume/MFTDomain/servers/mft_server1/logs/mft_server1-diagnostic.log
  enabled: true

- type: filestream
  id: mftcontainer-mftserver1-mft-diagnostic-logs
  include_lines: ['^\[[0-9]{4}\-[0-9]{2}\-[0-9]{2}']
  exclude_lines: ['\[NOTIFICATION\]']
  tags: ["mftcontainer-mftserver1-mft-diagnostic-logs"]
  paths:
  - /usr/share/logs/MFTVolume/MFTDomain/servers/mft_server1/logs/mft_server1-mft-diagnostic.log
  enabled: true

- type: filestream
  id: mftcontainer-mftserver1-out-logs
  include_lines: ['^<[0-9]{2}']
  exclude_lines: [' INFO ']
  tags: ["mftcontainer-mftserver1-out-logs"]
  paths:
  - /usr/share/logs/MFTVolume/MFTDomain/servers/mft_server1/logs/mft_server1.out
  enabled: true

output.logstash:
  hosts: 
    - logstash:5044
